# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171007_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='individualitem',
            name='name',
        ),
    ]
